In [1]:
import pandas as pd
import os

def convert_dir_to_csv(dir_path):
    files = os.listdir(dir_path)
    files.remove('list.csv')
    dataset_dict ={"category":[], "articles":[]}
    for i in files:
        with open(dir_path+'/'+i, 'r+',encoding='latin1') as f:
            dataset_dict["articles"].append(f.read())
        dataset_dict["category"].append(i[:len(i)-4])

    df = pd.DataFrame(dataset_dict)
    return df

dataframe = convert_dir_to_csv('20_NewsGroups')

In [2]:
import pandas as pd
import os

def convert_dir_to_csv(dir_path):
    files2 = os.listdir(dir_path)
    dataset_dict2 ={"category":[], "articles":[]}
    for i in files2:
        with open(dir_path+'/'+i, 'r+',encoding='latin1') as f:
            dataset_dict2["articles"].append(f.read())
        dataset_dict2["category"].append(i[:len(i)-4])

    df = pd.DataFrame(dataset_dict2)
    return df



testing = convert_dir_to_csv('testing')


In [3]:
dataframe

category  \
0                alt.atheism   
1              comp.graphics   
2    comp.os.ms-windows.misc   
3   comp.sys.ibm.pc.hardware   
4      comp.sys.mac.hardware   
5             comp.windows.x   
6               misc.forsale   
7                  rec.autos   
8            rec.motorcycles   
9         rec.sport.baseball   
10          rec.sport.hockey   
11                 sci.crypt   
12           sci.electronics   
13                   sci.med   
14                 sci.space   
15    soc.religion.christian   
16        talk.politics.guns   
17     talk.politics.mideast   
18        talk.politics.misc   
19        talk.religion.misc   

                                             articles  
0   From: mathew <mathew@mantis.co.uk>\nSubject: A...  
1   From: lipman@oasys.dt.navy.mil (Robert Lipman)...  
2   Newsgroup: comp.os.ms-windows.misc\ndocument_i...  
3   Newsgroup: comp.sys.ibm.pc.hardware\ndocument_...  
4   Newsgroup: comp.sys.mac.hardware\ndocument_id:...  
5   Newsgroup: comp.windows.x\ndocument_id: 64830\...  
6   Newsgroup: misc.forsale\ndocument_id: 70337\nF...  
7   Newsgroup: rec.autos\ndocument_id: 101551\nFro...  
8   Newsgroup: rec.motorcycles\ndocument_id: 10172...  
9   Newsgroup: rec.sport.baseball\ndocument_id: 10...  
10  Newsgroup: rec.sport.hockey\ndocument_id: 5255...  
11  Newsgroup: sci.crypt\ndocument_id: 14147\nFrom...  
12  Newsgroup: sci.electronics\ndocument_id: 52434...  
13  Newsgroup: sci.med\ndocument_id: 57110\nFrom: ...  
14  Newsgroup: sci.space\ndocument_id: 59497\nFrom...  
15  Newsgroup: soc.religion.christian\ndocument_id...  
16  Newsgroup: talk.politics.guns\ndocument_id: 53...  
17  Newsgroup: talk.politics.mideast\ndocument_id:...  
18  Newsgroup: talk.politics.misc\ndocument_id: 12...  
19  Newsgroup: talk.religion.misc\ndocument_id: 82...

In [4]:
testing

category                                           articles
0     rec.sport.baseball  Henry Aaron, who died in January, will forever...
1              sci.space  Being able to accurately detect changes to Ear...
2  talk.politics.mideast  Prime Minister Benjamin Netanyahu’s party wo...

In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Input, GlobalMaxPooling1D
from tensorflow.keras.layers import LSTM,Embedding
from tensorflow.keras.models import Model

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [6]:
dataframe['b_labels']=dataframe['category'].map({"alt.atheism":0,"comp.graphics":1,"comp.os.ms-windows.misc":2,"comp.sys.ibm.pc.hardware":3,
                "comp.sys.mac.hardware":4,"comp.windows.x":5,"misc.forsale":6,"rec.autos":7,"rec.motorcycles":8,
                "rec.sport.baseball":9,"rec.sport.hockey":10,"sci.crypt":11,"sci.electronics":12,"sci.med":13,
                "sci.space":14,"soc.religion.christian":15,"talk.politics.guns":16,"talk.politics.mideast":17,
                "talk.politics.misc":18,"talk.religion.misc":19})
Y=dataframe['b_labels'].values

In [7]:
testing['b_labels']=testing['category'].map({"rec.sport.baseball":9,"sci.space":14,"talk.politics.mideast":17})

In [8]:
dataframe

category  \
0                alt.atheism   
1              comp.graphics   
2    comp.os.ms-windows.misc   
3   comp.sys.ibm.pc.hardware   
4      comp.sys.mac.hardware   
5             comp.windows.x   
6               misc.forsale   
7                  rec.autos   
8            rec.motorcycles   
9         rec.sport.baseball   
10          rec.sport.hockey   
11                 sci.crypt   
12           sci.electronics   
13                   sci.med   
14                 sci.space   
15    soc.religion.christian   
16        talk.politics.guns   
17     talk.politics.mideast   
18        talk.politics.misc   
19        talk.religion.misc   

                                             articles  b_labels  
0   From: mathew <mathew@mantis.co.uk>\nSubject: A...         0  
1   From: lipman@oasys.dt.navy.mil (Robert Lipman)...         1  
2   Newsgroup: comp.os.ms-windows.misc\ndocument_i...         2  
3   Newsgroup: comp.sys.ibm.pc.hardware\ndocument_...         3  
4   Newsgroup: comp.sys.mac.hardware\ndocument_id:...         4  
5   Newsgroup: comp.windows.x\ndocument_id: 64830\...         5  
6   Newsgroup: misc.forsale\ndocument_id: 70337\nF...         6  
7   Newsgroup: rec.autos\ndocument_id: 101551\nFro...         7  
8   Newsgroup: rec.motorcycles\ndocument_id: 10172...         8  
9   Newsgroup: rec.sport.baseball\ndocument_id: 10...         9  
10  Newsgroup: rec.sport.hockey\ndocument_id: 5255...        10  
11  Newsgroup: sci.crypt\ndocument_id: 14147\nFrom...        11  
12  Newsgroup: sci.electronics\ndocument_id: 52434...        12  
13  Newsgroup: sci.med\ndocument_id: 57110\nFrom: ...        13  
14  Newsgroup: sci.space\ndocument_id: 59497\nFrom...        14  
15  Newsgroup: soc.religion.christian\ndocument_id...        15  
16  Newsgroup: talk.politics.guns\ndocument_id: 53...        16  
17  Newsgroup: talk.politics.mideast\ndocument_id:...        17  
18  Newsgroup: talk.politics.misc\ndocument_id: 12...        18  
19  Newsgroup: talk.religion.misc\ndocument_id: 82...        19

In [9]:
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [10]:
MAX_VOCAB_SIZE=200000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)

In [11]:
tokenizer.fit_on_texts(dataframe['articles'])

In [12]:
sequence_train=tokenizer.texts_to_sequences(dataframe['articles'])
sequence_test=tokenizer.texts_to_sequences(testing['articles'])

In [13]:
word2idx=tokenizer.word_index
V=len(word2idx)
print("Found %s unique tokens." %V)

Found 190934 unique tokens.


In [14]:
data_train=pad_sequences(sequence_train)
print("Shape of data train tensor: ",data_train.shape)
T=data_train.shape[1]

Shape of data train tensor:  (20, 1002128)


In [15]:
data_test=pad_sequences(sequence_test,maxlen=T)
print("Shape of data test tensor: ",data_test.shape)


Shape of data test tensor:  (3, 1002128)


In [16]:
D=20
M=15
i=Input(shape=(T,))
x=Embedding(V+1,D)(i)
x=LSTM(M,return_sequences=True)(x)
x=GlobalMaxPooling1D()(x)
x=Dense(20,activation='softmax')(x)
model=Model(i,x)

In [17]:
model.compile(
        loss='sparse_categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])



In [18]:
Ytest=testing['b_labels'].values

In [19]:
data_train

array([[    0,     0,     0, ..., 11975,  7424, 27199],
       [    0,     0,     0, ...,   207,     6,   716],
       [   31,   119,   348, ...,    16,   177,   207],
       ...,
       [    0,     0,     0, ...,   488, 16826, 14403],
       [    0,     0,     0, ...,  8629, 14610,   985],
       [    0,     0,     0, ...,     3,     1,  1663]])

In [20]:
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [21]:
data_test

array([[   0,    0,    0, ...,   11,  253,   50],
       [   0,    0,    0, ..., 1183,  182,   35],
       [   0,    0,    0, ...,    1, 4183, 1206]])

In [22]:
Ytest

array([ 9, 14, 17], dtype=int64)

In [23]:
pd.DataFrame(data_train).to_csv('news.csv')

In [ ]:
print("Training model....")
r=model.fit(
data_train,
Y,
epochs=5,
validation_data=(data_test,Ytest))

Training model....
Epoch 1/5
