In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [3]:
df=pd.read_csv("weatherAUS.csv")

In [4]:
df

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0   
1            NaN         WNW           44.0        NNW  ...        44.0   
2            NaN         WSW           46.0          W  ...        38.0   
3            NaN          NE           24.0         SE  ...        45.0   
4            NaN           W           41.0        ENE  ...        82.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[145460 rows x 23 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null

In [6]:
df.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm  
count  89572.000000  86102.000000  143693.000000  141851.00000  
mean       4.447461      4.509930      16.990631      21.68339  
std        2.887159      2.720357       6.488753       6.93665  
min        0.000000      0.000000      -7.200000      -5.40000  
25%        1.000000      2.000000      12.300000      16.60000  
50%        5.000000      5.000000      16.700000      21.10000  
75%        7.000000      7.000000      21.600000      26.40000  
max        9.000000      9.000000      40.200000      46.70000

##  CLEANING THE DATA

In [7]:
df_2=df.fillna(method='bfill',axis=0).fillna(0)

In [8]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        145460 non-null  float64
 3   MaxTemp        145460 non-null  float64
 4   Rainfall       145460 non-null  float64
 5   Evaporation    145460 non-null  float64
 6   Sunshine       145460 non-null  float64
 7   WindGustDir    145460 non-null  object 
 8   WindGustSpeed  145460 non-null  float64
 9   WindDir9am     145460 non-null  object 
 10  WindDir3pm     145460 non-null  object 
 11  WindSpeed9am   145460 non-null  float64
 12  WindSpeed3pm   145460 non-null  float64
 13  Humidity9am    145460 non-null  float64
 14  Humidity3pm    145460 non-null  float64
 15  Pressure9am    145460 non-null  float64
 16  Pressure3pm    145460 non-null  float64
 17  Cloud9am       145460 non-nul

In [9]:
df_2.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6         12.0      12.3   
1  2008-12-02   Albury      7.4     25.1       0.0         12.0      12.3   
2  2008-12-03   Albury     12.9     25.7       0.0         12.0      12.3   
3  2008-12-04   Albury      9.2     28.0       0.0         12.0      12.3   
4  2008-12-05   Albury     17.5     32.3       1.0         12.0      12.3   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       2.0     16.9     21.8         No   
1       1010.6       1007.8       7.0       2.0     17.2     24.3         No   
2       1007.6       1008.7       7.0       2.0     21.0     23.2         No   
3       1017.6       1012.8       7.0       8.0     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [10]:
def converter(x):
    if x=='Yes':
        return 1
    else:
        return 0

In [11]:
data=df_2.drop(['Date','Location','WindGustDir','WindDir9am','WindDir3pm'],axis=1)
data['RainTod']=data['RainToday'].apply(converter)
data['RainTom']=data['RainTomorrow'].apply(converter)
data.drop(['RainToday','RainTomorrow'],axis=1,inplace=True)
data

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0          13.4     22.9       0.6         12.0      12.3           44.0   
1           7.4     25.1       0.0         12.0      12.3           44.0   
2          12.9     25.7       0.0         12.0      12.3           46.0   
3           9.2     28.0       0.0         12.0      12.3           24.0   
4          17.5     32.3       1.0         12.0      12.3           41.0   
...         ...      ...       ...          ...       ...            ...   
145455      2.8     23.4       0.0          0.0       0.0           31.0   
145456      3.6     25.3       0.0          0.0       0.0           22.0   
145457      5.4     26.9       0.0          0.0       0.0           37.0   
145458      7.8     27.0       0.0          0.0       0.0           28.0   
145459     14.9      0.0       0.0          0.0       0.0            0.0   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0               20.0          24.0         71.0         22.0       1007.7   
1                4.0          22.0         44.0         25.0       1010.6   
2               19.0          26.0         38.0         30.0       1007.6   
3               11.0           9.0         45.0         16.0       1017.6   
4                7.0          20.0         82.0         33.0       1010.8   
...              ...           ...          ...          ...          ...   
145455          13.0          11.0         51.0         24.0       1024.6   
145456          13.0           9.0         56.0         21.0       1023.5   
145457           9.0           9.0         53.0         24.0       1021.0   
145458          13.0           7.0         51.0         24.0       1019.4   
145459          17.0          17.0         62.0         36.0       1020.2   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainTod  RainTom  
0            1007.1       8.0       2.0     16.9     21.8        0        0  
1            1007.8       7.0       2.0     17.2     24.3        0        0  
2            1008.7       7.0       2.0     21.0     23.2        0        0  
3            1012.8       7.0       8.0     18.1     26.5        0        0  
4            1006.0       7.0       8.0     17.8     29.7        0        0  
...             ...       ...       ...      ...      ...      ...      ...  
145455       1020.3       3.0       2.0     10.1     22.4        0        0  
145456       1019.1       3.0       2.0     10.9     24.5        0        0  
145457       1016.8       3.0       2.0     12.5     26.1        0        0  
145458       1016.5       3.0       2.0     15.1     26.0        0        0  
145459       1017.9       8.0       8.0     15.0     20.9        0        0  

[145460 rows x 18 columns]

##  DECISION TREE CLASSIFIER

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X=data.drop('RainTom',axis=1)
y=data['RainTom']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
dtree=DecisionTreeClassifier()

In [16]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [17]:
pred=dtree.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      0.85      0.86     36763
           1       0.53      0.53      0.53     11239

    accuracy                           0.78     48002
   macro avg       0.69      0.69      0.69     48002
weighted avg       0.78      0.78      0.78     48002



In [20]:
print(confusion_matrix(y_test,pred))

[[31406  5357]
 [ 5291  5948]]


##  RANDOM FOREST CLASSIFIER

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
RF=RandomForestClassifier()

In [23]:
RF.fit(X_train,y_train)

RandomForestClassifier()

In [24]:
pred=RF.predict(X_test)

In [25]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.91     36763
           1       0.77      0.50      0.61     11239

    accuracy                           0.85     48002
   macro avg       0.82      0.73      0.76     48002
weighted avg       0.84      0.85      0.84     48002



In [26]:
print(confusion_matrix(y_test,pred))

[[35061  1702]
 [ 5583  5656]]


##  SUPPORT VECTOR MACHINE

In [30]:
from sklearn.svm import SVC

In [31]:
svc=SVC()

In [32]:
svc.fit(X_train,y_train)

SVC()

In [33]:
pred=svc.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix,classification_report

In [35]:
print(confusion_matrix(y_test,pred))

[[35685  1078]
 [ 7466  3773]]


In [36]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89     36763
           1       0.78      0.34      0.47     11239

    accuracy                           0.82     48002
   macro avg       0.80      0.65      0.68     48002
weighted avg       0.82      0.82      0.79     48002



##  GRID SEARCH

In [37]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid={'C':[0.1,1],'gamma':[1,0.1]}

In [ ]:
gs=GridSearchCV(SVC(),param_grid,verbose=2)
gs.fit(X_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


In [ ]:
pred=gs.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,pred))

In [ ]:
print(classification_report(y_test,pred))

##  K MEANS CLUSTERING

In [27]:
from sklearn.cluster import KMeans

In [28]:
km=KMeans(2)

In [32]:
km.fit(X)

KMeans(n_clusters=2)

In [33]:
km.cluster_centers_

array([[1.14799068e+01, 2.03705658e+01, 3.86821424e+00, 5.82581942e+00,
        7.49869412e+00, 3.89550041e+01, 1.27566861e+01, 1.80881111e+01,
        8.05576111e+01, 6.44470848e+01, 1.01726508e+03, 1.01517496e+03,
        5.18004282e+00, 5.16664104e+00, 1.51528347e+01, 1.88906826e+01,
        3.41041625e-01],
       [1.32016333e+01, 2.71293160e+01, 5.92499877e-01, 8.12776802e+00,
        9.12939149e+00, 4.28606674e+01, 1.58162642e+01, 1.96109096e+01,
        5.27313482e+01, 3.38867020e+01, 1.01615347e+03, 1.01333405e+03,
        3.60112609e+00, 3.82200955e+00, 1.94569445e+01, 2.56404472e+01,
        8.06809042e-02]])

In [38]:
print(confusion_matrix(data['RainTom'],km.labels_))
print(classification_report(data['RainTom'],km.labels_))

[[56845 54871]
 [27851  5893]]
              precision    recall  f1-score   support

           0       0.67      0.51      0.58    111716
           1       0.10      0.17      0.12     33744

    accuracy                           0.43    145460
   macro avg       0.38      0.34      0.35    145460
weighted avg       0.54      0.43      0.47    145460



##  .....................................................................
##  Decision Tree Classifier Works The Best
##  .....................................................................